name: Java CI
on: [push]
jobs:
  jenkins-container-pipeline:
    strategy:
            fail-fast: false
            matrix:
                container:
                    - centos:8  # Updated to a version that includes GLIBC_2.28
                    - ubuntu:20.04
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    container:
      image: ghcr.io/jenkinsci/jenkinsfile-runner:master
    steps:
      - uses: actions/checkout@v4
      - uses:
          jenkinsci/jfr-container-action@master
        with:
          command: run
          jenkinsfile: Jenkinsfile
          pluginstxt: plugins.txt
          jcasc: jcasc.yml
