name: Java CI
on: [push]
jobs:
  jenkins-container-pipeline:
    runs-on: ubuntu:18.04
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    container:
      image: ghcr.io/jenkinsci/jenkinsfile-runner:master
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/checkout@v2
      - uses:
          jenkinsci/jfr-container-action@master
        with:
          command: run
          jenkinsfile: Jenkinsfile
          pluginstxt: plugins.txt
          jcasc: jcasc.yml
